### ISSUE TITLE
type: there could be a type for URL in link util function to prevent raw string to be passed as a valid url

### ISSUE THREAD

**Issue by mahdikhashan** [unjs/omark#9]
right now, any string can be passed as a valid url to the link function as the first argument, but it can be anything from `a-simple-url` to `http://random-url.net` or `#`. 

I would suggest to have a custom type instead of **string** for this argument.

**Comment by pi0** [comment]
Thanks for the suggestion. Yes, indeed user input could be anything. But by making types more strict, we make usage harder. 

The URL constructor could be also a nice option to additionally support (and PR welcome if you like to) only it does not support relative URLs without protocol like `[src](./src/index.ts)` so we don't have many options here.
